version: '3.8'

services:

  backend:
    build: backend
    hostname: localhost
    # volumes:
    #   - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - ares-network

  frontend:
    build: frontend
    hostname: frontend-host
    # volumes:
    #   - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - ares-network

networks:
  ares-network: {}
